export { default as Home } from './Home.jsx'
export { default as About } from './About.jsx'
export { default as Portfolio } from './Portfolio.jsx'
export { default as Blog } from './Blog.jsx'
export { default as Contact } from './Contact.jsx'